### ISSUE TITLE
"Connecting to ollama server localhost"

### ISSUE THREAD

**Issue by gingerbeardman** [sroecker/LLM_AppDev-HandsOn#4]
Please help.

1. running ollama macOS, icon is in the menu bar
2. forked and did venv
3. questions to the bot result in a blank response
4. terminal shows "Connecting to ollama server localhost"

What am I missing?

Thanks!

<img width="822" alt="Screen shot 2024-03-06 at 15 34 58" src="https://github.com/sroecker/LLM_AppDev-HandsOn/assets/49612/86e6b1bc-1481-4f20-8051-ad9d94d906a6">

**Comment by sroecker** [comment]
Can you stop ollama and run ollama serve manually?

**Comment by gingerbeardman** [comment]
It seems I needed to do one of the later steps before I could reproduce the animation of the chat working.

I needed to download the zephyr model!
